### PR TITLE
Update to io.prestosql

### PR DESCRIPTION
**Pull request by iijima-satoshi**
- Update groupId to io.prestosql
- Upgrade Hive JDBC driver for io.prestosql

I have confirmed that the build is successful on presto v332
`mvn clean package -Dpresto.version=332 -DskipTests`

### CODE REVIEW

**Comment by findepi** [comment]
@iijima-satoshi thanks for your PR.

I guess you are aware presto-yarn is deprecated and we encourage other deployment methods.
(see https://prestosql.io/docs/current/installation/deployment.html)

having said that -- if you want to update this repo, i will be happy to help in my free time.
For this PR, please make sure to update `presto.version` in pom.xml as well.

**Comment by iijima-satoshi** [comment]
Thank you for your reviewing.
I fixed `presto.version`. I will submit the signed CLA later.
I know presto-yarn is deprecated and am considering other deployment methods for the future.

**Comment by iijima-satoshi** [comment]
I have sent the signed CLA and will wait to be added to the contributor list.

**Comment by findepi** [comment]
@iijima-satoshi i merged https://github.com/prestosql/presto-yarn/pull/2 so that we will be able to release.
Can you please rebase to let the CI re run?

**Comment by iijima-satoshi** [comment]
Thank you for your supporting and preparing for the release.
I will again run the CI as soon as I am added to contributor list.

**Comment by iijima-satoshi** [comment]
@findepi All CI passed. Could you please merge this?

**Comment by kokosing** [comment]
@iijima-satoshi Have you had a chance to actually test it that it works?

**Review by kokosing — APPROVED** [review]

**Comment by iijima-satoshi** [comment]
@kokosing It works well in my hadoop environment as with presto-yarn using prestodb.

**Comment by kokosing** [comment]
Great to hear that!

Would you be now interested in updating this to 337?

**Comment by iijima-satoshi** [comment]
As presto 333 or later requires JDK 11+, I would like to try it in the future.
Unfortunately, my hadoop yarn cluster is running using JDK 8 now.

**Comment by iijima-satoshi** [comment]
@kokosing Thank you for merging this pr!

**Pull request merged**
